### ISSUE TITLE
Failed with Mac OS X Mountain Lion

### ISSUE THREAD

**Issue by ghost** [jweslley/rails_completion#11]
-bash: /Users/weizhifeng/.rails.bash: line 38: syntax error in conditional expression: unexpected token `('
-bash: /Users/weizhifeng/.rails.bash: line 38: syntax error near`@($'
-bash: /Users/weizhifeng/.rails.bash: line 38: `    if [[ ${COMP_WORDS[i]} == @($any_command) ]]; then'

**Comment by jweslley** [comment]
Hi Jeremy,

I guess you are using zsh instead of bash. right?! Currently rails_completion only works on bash, but I have plans to work in a zsh version soon.

**Comment by ghost** [comment]
@jweslley I'm sure that i'm using bash, below is my system info:

$ uname -a
Darwin MacBookPro 12.0.0 Darwin Kernel Version 12.0.0: Sun Jun 24 23:00:16 PDT 2012; root:xnu-2050.7.9~1/RELEASE_X86_64 x86_64

$ echo $SHELL
/bin/bash

**Comment by jweslley** [comment]
@JeremyWei what is your bash version?

**Comment by ghost** [comment]
@jweslley this is my bash version:
$ bash -version
GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin12) 
Copyright (C) 2007 Free Software Foundation, Inc.

**Comment by jweslley** [comment]
my current bash version is 4.2 -- GNU bash, version 4.2.24(1)-release (i686-pc-linux-gnu)

Can you upgrade your bash?

**Comment by ghost** [comment]
@jweslley thanks. i will try it later.

**Comment by ghost** [comment]
@jweslley when i update bash to 4.2.x, then it works. thanks. 

$ brew install bash

**Comment by jweslley** [comment]
\o/
