### ISSUE TITLE
Add to readme - update bash on MacOsX

### ISSUE THREAD

**Issue by prcaen** [jweslley/rails_completion#13]
Use last version of bash:

``` shell
brew install bash
```

``` shell
sudo rm /bin/bash
sudo ln -s /usr/local/Cellar/bash/YOUR_VERSION/bin/bash /bin/bash
```

**Comment by engeld** [comment]
Yep, this one had me hanging at the start. I wasn't aware that bash v4 was required and (unsuccessfully) tried to make it work with bash v3.
