### ISSUE TITLE
Can't find the rails-completion on brew

### ISSUE THREAD

**Issue by simonweil** [jweslley/rails_completion#18]
This is the output of running the command as indicated in the readme.

> brew install rails-completion
> Error: No available formula for rails-completion 
> Searching taps...

I did run the tap command successfully.

**Comment by interior-night** [comment]
Working fine for me in that i can install it... but it doesn't appear to be actually doing anything (on OS X Mavericks with Bash 4.2.45)

**Comment by simonweil** [comment]
Well now it does work for me, no idea what changed and it works fine in rails 3 but not helpfull in rails 4.

**Comment by jweslley** [comment]
@simonweil I not updated rails_completion to support rails 4 yet! :(

**Comment by simonweil** [comment]
Well, thank you for what you have done!
