### ISSUE TITLE
_get_comp_words_by_ref command not found 

### ISSUE THREAD

**Issue by andhapp** [jweslley/rails_completion#2]
Hello,

I get _get_comp_words_by_ref command not found error on Mac OS X when I do:

<pre>

rails c&lt;tab&gt;&lt;tab&gt;

-bash: _get_comp_words_by_ref: command not found

c        console  
</pre>

Anuj
@andhapp

**Comment by jweslley** [comment]
Are you using bash? If yes, do you have bash completion installed?

**Comment by andhapp** [comment]
Yup. It works ok with git completion though.

**Comment by jweslley** [comment]
The __get_comp_words_by_ref_ function is delivered by bash_completion 1.1+. Can you check your bash_completion version? This function can be found in `/etc/bash_completion` file.

**Comment by zaki** [comment]
Installing bash-completion (1.2) through brew (`brew install bash-completion`) solved the issue for me, it might work for you too.

**Comment by andhapp** [comment]
Thanks. Fixed it. Apparently, I had the older version and the install instructions can be found here:
http://bash-completion.alioth.debian.org/

**Comment by set5think** [comment]
is this not working with bash-completion 2.0?

**Comment by jweslley** [comment]
@set5think  I'm using bash-completion 2.0 and it works fine. Had you run `bundle install`?

**Comment by set5think** [comment]
It was actually an iterm issue mixed with macports, I had to explicitly set the bash iterm was loading.

**Comment by kineticz** [comment]
In my case I had to reinstall bash-completion with brew.

**Comment by KeithTt** [comment]
good job!

**Comment by marchmallow** [comment]
I hit this with helm 2.9.1 and bash autocompletion 1.3_3 on Mac OS Sierra.. reinstalling bash completion via brew did not help.

**Comment by jontejj** [comment]
I fixed my problem with this by putting:
```
. /usr/local/etc/profile.d/bash_completion.sh
```

into my .bash_profile. (On Mac)

**Comment by taitelman** [comment]
managed to get it working in MacOS 12.5 by fixing some file permissions. using bash 5.1.16
in terminal type:
```
brew install bash
chsh -s /opt/homebrew/Cellar/bash/5.1.16/bin/bash
brew install bash-completion@2
ls -la /opt/homebrew/etc/profile.d/bash_completion.sh

lrwxr-xr-x  1 myuser  admin  68 Aug  2 17:19 /opt/homebrew/etc/profile.d/bash_completion.sh -> ../../Cellar/bash-completion@2/2.11/etc/profile.d/bash_completion.sh
```
but the symbolic link target! had no executable flag so:
```
chmod +x /opt/homebrew/Cellar/bash-completion\@2/2.11/etc/profile.d/bash_completion.sh
``` 

then edit your `~/.bash_profile` :
```
if [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]]; then 
. "/opt/homebrew/etc/profile.d/bash_completion.sh"
echo "installed bash auto completions"
fi

source <(kubectl completion bash)
alias k=kubectl
```
